services:
  backend-hackspain:
    container_name: hackspain_backend
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres-hackspain:5432/${POSTGRES_DB:-hackspain}
      - UV_PROJECT_ENVIRONMENT=/opt/venv
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres-hackspain:
        condition: service_healthy
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - appnet_hackspain

  postgres-hackspain:
    container_name: hackspain_db
    image: postgres:16-alpine
    build:
      context: .
      dockerfile: docker/postgresql.Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-hackspain}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_hackspain:/var/lib/postgresql/data
    networks:
      - appnet_hackspain
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend-hackspain:
    container_name: hackspain_frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    command: bun run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - "3000:5173"
    depends_on:
      - backend-hackspain
    networks:
      - appnet_hackspain

volumes:
  postgres_data_hackspain:

networks:
  appnet_hackspain:
